### ISSUE TITLE
Error during collapsing cluster

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/arakoon#123]
version: 1.9.8

```
2016-08-22 10:12:06 06900 +0200 - ovs-01.be-gen8-2 - 9182/140488436619072 - lib/scheduled tasks - 334276 - ERROR - Error during collapsing cluster ovsdb node jNkeV9q1hhm8IGRk
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/scheduledtask.py", line 411, in collapse_arakoon
    client.collapse(str(node), 2)
  File "<update_argspec>", line 5, in collapse
  File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 152, in wrapped
    raise new_exception
ArakoonException: unknown failure
```

**Comment by matthiasdeblock** [comment]
Same issue: https://github.com/openvstorage/arakoon/issues/111
